version: '2'
services:
  angular:
    build: ./paired-associate-task
    ports:
      - "80:80"
  django:
    build: ./pairs_api
    # command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=composetest
      - MYSQL_PASSWORD=testpassword
      - MYSQL_DATABASE=composetest
