version: '2'
services:
  angular-nginx:
    container_name: angular-nginx
    build: ./paired-associate-task
    ports:
      - "80:80"
    links:
      - pairs_api
    depends_on:
      - pairs_api
  pairs_api:
    container_name: pairs_api
    build: ./pairs_api
    # command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - pairs_db
    depends_on:
      - pairs_db
  pairs_db:
    image: mysql:latest
    container_name: pairs_db
    environment:
      - MYSQL_ROOT_PASSWORD=dogchair
      - MYSQL_DATABASE=pairassociates
